[package]
name = "configger"
version = "0.1.0"
authors = ["arsalan86 <public@arsalanpirzada.com>"]

[dependencies]
#inotify = "0.4"
inotify = { git = "https://github.com/arsalan86/inotify-rs.git", branch = "derive-hash" }
serde_json = "1.0"
serde_derive = "1.0.10"
serde = "1.0.10"
blake2 = "0.6.1"